# https://github.com/envygeeks/jekyll-docker/blob/master/repos/jekyll/Dockerfile
FROM jekyll/jekyll:3.7
RUN gem install \
    github-pages:180 \
    jekyll-archives:2.1.1 \
    stringex:2.8.4 \
    jekyll-feed:0.9.3 \
    jekyll-crosspost-to-medium:0.1.14 \
    jekyll-lunr-js-search:3.3.0 \
    liquid_pluralize:1.0.3 \
    minimal-mistakes-jekyll:4.5.1 \
  -- --use-system-libraries 
