FROM mhart/alpine-node:0.12.18

WORKDIR /app

# If you have native dependencies, you'll need extra tools
RUN apk add --no-cache make gcc g++ python

# If you need npm, don't use a base tag
# RUN npm install
